{% set name = "azure-mgmt-keyvault" %}
{% set version = "8.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 2c974c6114d8d27152642c82a975812790a5e86ccf609bf370a476d9ea0d2e7d

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - azure-common >=1.1,<2
    - msrest >=0.5.0
    - msrestazure >=0.4.32,<2.0.0
    - python

test:
  imports:
    - azure
    - azure.mgmt
    - azure.mgmt.keyvault
    - azure.mgmt.keyvault.v2016_10_01
    - azure.mgmt.keyvault.v2016_10_01.models
    - azure.mgmt.keyvault.v2016_10_01.operations
    - azure.mgmt.keyvault.v2018_02_14
    - azure.mgmt.keyvault.v2018_02_14.models
    - azure.mgmt.keyvault.v2018_02_14.operations

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Microsoft Azure Key Vault Management Client Library for Python
  doc_url: https://docs.microsoft.com/python/api/overview/azure/key-vault
  dev_url: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - andreyz4k
